import type { NextPage } from 'next'
import Head from 'next/head'
import { Layout } from '../components/Layout';
import Welcome from '../components/Welcome';
import { Title } from '../styles/GlobalComponents';

const Home: NextPage = () => {
  return (
    <Layout >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='center-plis'>
        <Title>Bem vindo Jovem Padawan</Title>
        <Welcome />
      </div>
    </Layout>
  )
}

export default Home
